openapi: 3.0.0
info:
  title: E-Commerce Live
  contact: {}
  version: '1.0'
servers:
- url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
  variables: {}
- url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
  variables: {}
paths:
  /register-user:
    post:
      tags:
      - User
      summary: Register
      operationId: Register
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            encoding: {}
            schema:
              required:
              - lastname
              - firstname
              - email
              - username
              - role
              - password
              - confirmpassword
              - image
              type: object
              properties:
                lastname:
                  type: string
                  example: Sosanyaewkf
                firstname:
                  type: string
                  example: Idriswjkcw
                email:
                  type: string
                  example: sunday.adesola94@gmail.comm
                username:
                  type: string
                  example: Alomawefh
                role:
                  type: string
                  example: user
                password:
                  type: string
                  example: Sosanya0.
                confirmpassword:
                  type: string
                  example: Sosanya0.
                image:
                  type: string
                  format: binary
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /get-user:
    post:
      tags:
      - User
      summary: Get User
      operationId: GetUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/GetUserRequest'
              - example:
                  email: sunday.adesola94@gmail.com
            example:
              email: sunday.adesola94@gmail.com
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /get-all-user:
    get:
      tags:
      - User
      summary: Get All User
      operationId: GetAllUser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /delete-user/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The user ID
    delete:
      tags:
      - User
      summary: Delete
      operationId: Delete
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /auth/verify-email/{token}:
    parameters:
      - in: path
        name: token
        schema:
          type: string
        required: true
        description: The token
    put:
      tags:
      - Auth
      summary: Email Verification
      operationId: EmailVerification
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /auth/verify-otp/{otp}:
    parameters:
      - in: path
        name: otp
        schema:
          type: string
        required: true
        description: otp
    post:
      tags:
      - Auth
      summary: Verify OTP
      operationId: VerifyOTP
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/VerifyOTPRequest'
              - example:
                  otp: DHZozSousL
            example:
              otp: DHZozSousL
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /auth/resend-otp/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: User ID
    post:
      tags:
      - Auth
      summary: Resend OTP
      operationId: ResendOTP
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /auth/forget-password:
    post:
      tags:
      - Auth
      summary: Forget Password
      operationId: ForgetPassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ForgetPasswordRequest'
              - example:
                  email: tnsosanya@student.oauife.edu.ng
            example:
              email: tnsosanya@student.oauife.edu.ng
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /auth/reset-password/{token}:
    parameters:
      - in: path
        name: token
        schema:
          type: string
        required: true
        description: token
    put:
      tags:
      - Auth
      summary: Reset Password
      operationId: ResetPassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ResetPasswordRequest'
              - example:
                  newPassword: Sosanya0.
                  confirmNewPassword: Sosanya0.
            example:
              newPassword: Sosanya0.
              confirmNewPassword: Sosanya0.
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /auth/update-profile:
    put:
      tags:
      - Auth
      summary: Update Profile
      operationId: UpdateProfile
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateProfileRequest'
              - example:
                  username: MallamTY
            example:
              username: MallamTY
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /auth/update-profile-picture:
    put:
      tags:
      - Auth
      summary: Update Profile Picture
      operationId: UpdateProfilePicture
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            encoding: {}
            schema:
              required:
              - image
              type: object
              properties:
                image:
                  type: string
                  format: binary
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /auth/login:
    post:
      tags:
      - Auth
      summary: Login
      operationId: Login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginRequest'
              - example:
                  username: Aloma
                  password: Sosanya0.
            example:
              username: Aloma
              password: Sosanya0.
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /product/upload:
    post:
      tags:
      - Product
      summary: Upload
      operationId: Upload
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            encoding: {}
            schema:
              required:
              - name
              - description
              - price
              - quantity
              - ratingsAverage
              - deliveryfee
              - images
              type: object
              properties:
                name:
                  type: string
                  example: Clothfhwueofh
                description:
                  type: string
                  example: Laptopfhwoeghe
                price:
                  type: integer
                  format: int32
                  example: 500
                quantity:
                  type: integer
                  format: int32
                  example: 10
                ratingsAverage:
                  type: integer
                  format: int32
                  example: 5
                deliveryfee:
                  type: integer
                  format: int32
                  example: 2000
                images:
                  type: string
                  format: binary
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /product/update/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Product ID
    put:
      tags:
      - Product
      summary: Update
      operationId: Update
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            encoding: {}
            schema:
              required:
              - images
              type: object
              properties:
                images:
                  type: string
                  format: binary
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /product/get-single/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: id
    get:
      tags:
      - Product
      summary: Get Single
      operationId: GetSingle
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /product/get-all:
    get:
      tags:
      - Product
      summary: Get All
      operationId: GetAll
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /product/delete/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Product ID
    delete:
      tags:
      - Product
      summary: Delete
      operationId: Delete1
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /cart/add:
    post:
      tags:
      - Cart
      summary: Add
      operationId: Add
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/AddRequest'
              - example:
                  product_id: 640a59de1e83492ddfdb048d
                  quantity: 2
            example:
              product_id: 640a59de1e83492ddfdb048d
              quantity: 2
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /cart/decrease-one:
    post:
      tags:
      - Cart
      summary: Decrease By One
      operationId: DecreaseByOne
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/DecreaseByOneRequest'
              - example:
                  product_id: 640a526ac848f0fdc89d3a4c
            example:
              product_id: 640a526ac848f0fdc89d3a4c
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /cart/increase-one:
    post:
      tags:
      - Cart
      summary: Increase By One
      operationId: IncreaseByOne
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/IncreaseByOneRequest'
              - example:
                  product_id: 640a526ac848f0fdc89d3a4c
            example:
              product_id: 640a526ac848f0fdc89d3a4c
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /cart/get-product:
    get:
      tags:
      - Cart
      summary: Get Product
      operationId: GetProduct
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /cart/delete-product/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Cart ID
    delete:
      tags:
      - Cart
      summary: Delete Carted Product
      operationId: DeleteCartedProduct
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /cart/delete:
    delete:
      tags:
      - Cart
      summary: Delete Cart
      operationId: DeleteCart
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /favourite/add-or-remove:
    post:
      tags:
      - Favourites
      summary: Add or Remove
      operationId: AddorRemove
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/AddorRemoveRequest'
              - example:
                  product_id: 640a526ac848f0fdc89d3a4c
            example:
              product_id: 640a526ac848f0fdc89d3a4c
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /favourite/get:
    get:
      tags:
      - Favourites
      summary: Get Favourites
      operationId: GetFavourites
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /favourite/check-product:
    post:
      tags:
      - Favourites
      summary: Check Product
      operationId: CheckProduct
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CheckProductRequest'
              - example:
                  product_id: 640a526ac848f0fdc89d3a4c
            example:
              product_id: 640a526ac848f0fdc89d3a4c
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /favourite/delete:
    delete:
      tags:
      - Favourites
      summary: Delete
      operationId: Delete2
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /auth/add-delivery:
    post:
      tags:
      - Delivery
      summary: Add
      operationId: PostAdd
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/AddRequest1'
              - example:
                  state: nassarawa
                  deliveryfee: 10000
            example:
              state: nassarawa
              deliveryfee: 10000
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /auth/update-delivery/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Delivery ID
    put:
      tags:
      - Delivery
      summary: Updated
      operationId: Updated
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdatedRequest'
              - example:
                  deliveryfee: '7500'
            example:
              deliveryfee: '7500'
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /auth/remove-delivery/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Delivery ID
    delete:
      tags:
      - Delivery
      summary: Delete
      operationId: Delete3
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /checkout/delivery:
    post:
      tags:
      - Checkout
      summary: Delivery
      operationId: Delivery
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/DeliveryRequest'
              - example:
                  doordelivery: Adam and Eve building, Ile-Ife
                  state: lagos
                  contact_person_name: Temitayo Sosanya
                  contact_person_phone: '123456789'
                  shipping_method: express
            example:
              doordelivery: Adam and Eve building, Ile-Ife
              state: lagos
              contact_person_name: Temitayo Sosanya
              contact_person_phone: '123456789'
              shipping_method: express
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /checkout/verify-payment:
    post:
      tags:
      - Checkout
      summary: Verify Payment
      operationId: VerifyPayment
      parameters:
      - name: txref
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 00g7xa7fucvwzrzqnhl6
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /order/get-single:
    post:
      tags:
      - Order
      summary: Get SIngle Order
      operationId: GetSIngleOrder
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/GetSIngleOrderRequest'
              - example:
                  reference: 00g7xa7fucvwzrzqnhl6
            example:
              reference: 00g7xa7fucvwzrzqnhl6
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /order/get-all:
    get:
      tags:
      - Order
      summary: Get All Order
      operationId: GetAllOrder
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /order/update:
    put:
      tags:
      - Order
      summary: Update Order
      operationId: UpdateOrder
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateOrderRequest'
              - example:
                  order_id: 640c8832786eae865f1ebb74
                  status: Delivered
                  delivered: true
            example:
              order_id: 640c8832786eae865f1ebb74
              status: Delivered
              delivered: true
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
  /order/delete:
    post:
      tags:
      - Order
      summary: Delete
      operationId: PostDelete
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/DeleteRequest'
              - example:
                  order_id: 640a6f8c12da0b9c504b61ff
            example:
              order_id: 640a6f8c12da0b9c504b61ff
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://mallamty-ecommerce.herokuapp.com/ecommerce/v1
        variables: {}
components:
  schemas:
    GetUserRequest:
      title: GetUserRequest
      required:
      - email
      type: object
      properties:
        email:
          type: string
      example:
        email: sunday.adesola94@gmail.com
    VerifyOTPRequest:
      title: VerifyOTPRequest
      required:
      - otp
      type: object
      properties:
        otp:
          type: string
      example:
        otp: DHZozSousL
    ForgetPasswordRequest:
      title: ForgetPasswordRequest
      required:
      - email
      type: object
      properties:
        email:
          type: string
      example:
        email: tnsosanya@student.oauife.edu.ng
    ResetPasswordRequest:
      title: ResetPasswordRequest
      required:
      - newPassword
      - confirmNewPassword
      type: object
      properties:
        newPassword:
          type: string
        confirmNewPassword:
          type: string
      example:
        newPassword: Sosanya0.
        confirmNewPassword: Sosanya0.
    UpdateProfileRequest:
      title: UpdateProfileRequest
      required:
      - username
      type: object
      properties:
        username:
          type: string
      example:
        username: MallamTY
    LoginRequest:
      title: LoginRequest
      required:
      - username
      - password
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: Aloma
        password: Sosanya0.
    AddRequest:
      title: AddRequest
      required:
      - product_id
      - quantity
      type: object
      properties:
        product_id:
          type: string
        quantity:
          type: integer
          format: int32
      example:
        product_id: 640a59de1e83492ddfdb048d
        quantity: 2
    DecreaseByOneRequest:
      title: DecreaseByOneRequest
      required:
      - product_id
      type: object
      properties:
        product_id:
          type: string
      example:
        product_id: 640a526ac848f0fdc89d3a4c
    IncreaseByOneRequest:
      title: IncreaseByOneRequest
      required:
      - product_id
      type: object
      properties:
        product_id:
          type: string
      example:
        product_id: 640a526ac848f0fdc89d3a4c
    AddorRemoveRequest:
      title: AddorRemoveRequest
      required:
      - product_id
      type: object
      properties:
        product_id:
          type: string
      example:
        product_id: 640a526ac848f0fdc89d3a4c
    CheckProductRequest:
      title: CheckProductRequest
      required:
      - product_id
      type: object
      properties:
        product_id:
          type: string
      example:
        product_id: 640a526ac848f0fdc89d3a4c
    AddRequest1:
      title: AddRequest1
      required:
      - state
      - deliveryfee
      type: object
      properties:
        state:
          type: string
        deliveryfee:
          type: integer
          format: int32
      example:
        state: nassarawa
        deliveryfee: 10000
    UpdatedRequest:
      title: UpdatedRequest
      required:
      - deliveryfee
      type: object
      properties:
        deliveryfee:
          type: string
      example:
        deliveryfee: '7500'
    DeliveryRequest:
      title: DeliveryRequest
      required:
      - doordelivery
      - state
      - contact_person_name
      - contact_person_phone
      - shipping_method
      type: object
      properties:
        doordelivery:
          type: string
        state:
          type: string
        contact_person_name:
          type: string
        contact_person_phone:
          type: string
        shipping_method:
          type: string
      example:
        doordelivery: Adam and Eve building, Ile-Ife
        state: lagos
        contact_person_name: Temitayo Sosanya
        contact_person_phone: '123456789'
        shipping_method: express
    GetSIngleOrderRequest:
      title: GetSIngleOrderRequest
      required:
      - reference
      type: object
      properties:
        reference:
          type: string
      example:
        reference: 00g7xa7fucvwzrzqnhl6
    UpdateOrderRequest:
      title: UpdateOrderRequest
      required:
      - order_id
      - status
      - delivered
      type: object
      properties:
        order_id:
          type: string
        status:
          type: string
        delivered:
          type: boolean
      example:
        order_id: 640c8832786eae865f1ebb74
        status: Delivered
        delivered: true
    DeleteRequest:
      title: DeleteRequest
      required:
      - order_id
      type: object
      properties:
        order_id:
          type: string
      example:
        order_id: 640a6f8c12da0b9c504b61ff
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: User
- name: Auth
- name: Product
- name: Cart
- name: Favourites
- name: Delivery
- name: Checkout
- name: Order